#!/bin/bash

  cd /opt/contrail/contrail_install_repo
  dpkg -i libnl-3-200_3.2.21-1ubuntu4_amd64.deb libc6*

  wget http://launchpadlibrarian.net/264517293/libexpat1_2.1.0-4ubuntu1.3_amd64.deb
  dpkg -i libexpat1_2.1.0-4ubuntu1.3_amd64.deb

  apt-get install nova-compute -y
  apt-get -f install -y
  apt-get install nova-compute -y
